GET http://localhost:5000/api/users
###

GET http://localhost:5000/api/users/auth/facebook/
# Content-Type: application/json

# {
#    "access_token": "EAAJLtPu1nFQBAGBM4wHzTY692rY6VrWKLWrYsLzGY3sguNGy8Itv1sjNGAKvSJBBDQusjdKJZCGbxvZBneCTBfkiH51m09LMkiuBbPeDnrfC0CDoftIsUg8ojCqdZATwXP1M0PnbLxYm3r1ZCoT3ORO5CuoRiTQZD"
# }
