GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/auth/facebook

###

POST http://localhost:3000/api/auth/register
content-type: application/json

{
   "first_name": "mother",
   "last_name": "",
   "email": "sammy@gmail.com",
   "password": "thingthing",
   "password_confirm": "thingthing"
}

###

POST http://localhost:3000/api/auth/login/jwt
content-type: application/json

{
   "email": "agentsmith@thematrix.com",
   "password": "password"
}